const {test,expect}=require('@playwright/test');
test.use({viewport:{width:1180,height:734},deviceScaleFactor:2,hasTouch:true});
test('Atlas actual two-finger walking and looking stay in the lane with accessible controls',async({page},info)=>{
 test.skip(info.project.name!=='desktop-chromium'||process.env.ATLAS_WEBGPU_QA!=='1');test.setTimeout(240000);
 await page.addInitScript(()=>{Object.defineProperty(navigator,'platform',{get:()=> 'MacIntel'});Object.defineProperty(navigator,'maxTouchPoints',{get:()=>5});});
 await page.route('**/__dev/levels/*/editor-draft',r=>r.fulfill({json:{}}));
 await page.goto((process.env.ATLAS_EDITOR_URL||'http://127.0.0.1:4173')+'/?dev=editor&level=LVL-0001&debug3d=1');
 await page.locator('[data-graphics-action="toggle"]').click();await page.locator('[data-renderer-choice="atlas-3d"]').click();
 const snap=()=>page.evaluate(()=>window.eval('threeRenderer.snapshot')());
 await expect.poll(async()=>(await snap()).status,{timeout:180000}).toBe('ready');
 const move=page.locator('[data-three-move]'),look=page.locator('[data-three-look]');
 await expect(move).toBeVisible();await expect(look).toBeVisible();
 const m=await move.boundingBox(),l=await look.boundingBox();expect(l.width).toBe(m.width);
 const cdp=await page.context().newCDPSession(page);
 const left={id:1,x:m.x+m.width/2,y:m.y+m.height/2},right={id:2,x:l.x+l.width/2,y:l.y+l.height/2};
 const touch=(type,touchPoints)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints});
 const initial=await snap();
 await touch('touchStart',[left]);left.x+=40;await touch('touchMove',[left]);
 await expect.poll(async()=>(await snap()).camera[0]).toBeGreaterThan(initial.camera[0]+.4);
 expect((await snap()).movement.speed).toBe(4.8);
 expect((await snap()).yaw).toBe(initial.yaw);
 await touch('touchStart',[left,right]);right.x+=32;right.y-=15;await touch('touchMove',[left,right]);
 await expect.poll(async()=>(await snap()).yaw).toBeLessThan(initial.yaw-.15);
 await expect.poll(async()=>(await snap()).pitch).toBeGreaterThan(initial.pitch+.05);
 await page.waitForTimeout(600);expect((await snap()).movement.lane.distance).toBeLessThanOrEqual(1.200001);
 await touch('touchEnd',[right]);await expect.poll(async()=>(await snap()).input.lookId).toBeNull();
 expect((await snap()).input.moveId).not.toBeNull();
 await touch('touchEnd',[]);await page.waitForTimeout(100);
 const stopped=await snap();await page.waitForTimeout(200);const later=await snap();
 expect(later.camera).toEqual(stopped.camera);expect(later.yaw).toBe(stopped.yaw);
 await page.addStyleTag({content:'[data-tap-diagnostics]{visibility:hidden}'});
 await page.screenshot({path:info.outputPath('dual-controls-landscape.png')});
 await page.evaluate(()=>{window.eval('state.worldX=1697');window.eval('threeRenderer').lookAt(-.65,-.12);});
 await page.waitForTimeout(300);await page.screenshot({path:info.outputPath('temple-lane.png')});
 await page.setViewportSize({width:734,height:1180});await page.waitForTimeout(400);
 await expect(move).toBeVisible();await expect(look).toBeVisible();
 for(const control of [move,look])expect(await control.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);
 const action=page.locator('[data-three-interact]');
 if(await action.isVisible())expect(await action.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);
 await page.screenshot({path:info.outputPath('dual-controls-portrait.png')});
 await cdp.detach();
 const keyboardStart=await snap();await page.keyboard.down('a');
 await expect.poll(async()=>(await snap()).yaw).toBeGreaterThan(keyboardStart.yaw+.1);
 await page.keyboard.up('a');expect((await snap()).camera).toEqual(keyboardStart.camera);
 await page.locator('[data-graphics-action="toggle"]').click();await page.locator('[data-renderer-choice="illustrated"]').click();
 await expect(look).toHaveCount(0);await expect(page.locator('.worldArt')).toBeVisible();
});
