const {test,expect}=require('@playwright/test');
const base=process.env.ATLAS_EDITOR_URL||'http://127.0.0.1:4173';
test('display toggles do not rebuild the scene or alter gameplay, and survive redraw',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/?dev=editor&level=LVL-0001');
 const fps=page.locator('[data-display-toggle="fps"]'),debug=page.locator('[data-display-toggle="debug"]');
 await expect(fps).toHaveCount(0);await expect(debug).toHaveCount(0);
 await page.locator('[data-graphics-action="toggle"]').click();
 await expect(fps).toBeVisible();await expect(fps).toHaveAttribute('aria-pressed','false');
 await expect(page.locator('[data-fps-display]')).toBeHidden();
 await expect(page.locator('[data-tap-diagnostics]')).toHaveCount(0);
 const original=await page.evaluate(()=>{window.originalScene=document.querySelector('[data-world-stage]');return {x:window.eval('state.worldX'),storage:JSON.stringify(localStorage)};});
 const activate=async locator=>info.project.name==='ipad-landscape'?locator.tap():locator.click();
 await activate(fps);await expect(page.locator('[data-fps-display]')).toHaveText(/^\d+ FPS$/);
 const positions=await page.evaluate(()=>{const f=document.querySelector('[data-display-toggle="fps"]'),b=document.querySelector('[data-fps-display]').getBoundingClientRect();return {inside:Boolean(f.closest('[data-graphics-settings]')),right:b.right>innerWidth-30,top:b.top<50};});
 expect(positions).toEqual({inside:true,right:true,top:true});
 await activate(debug);await expect(page.locator('[data-tap-diagnostics]')).toBeVisible();
 await activate(debug);await expect(page.locator('[data-tap-diagnostics]')).toBeHidden();
 expect(await page.evaluate(()=>document.querySelector('[data-world-stage]')===window.originalScene)).toBe(true);
 expect(await page.evaluate(()=>({x:window.eval('state.worldX'),storage:JSON.stringify(localStorage)}))).toEqual(original);
 await page.evaluate(()=>window.eval('render')());await expect(fps).toHaveAttribute('aria-pressed','true');
 await expect(page.locator('[data-fps-display]')).toHaveText(/^\d+ FPS$/);
 await page.screenshot({path:info.outputPath('display-controls.png')});
 await activate(fps);await expect(page.locator('[data-fps-display]')).toBeHidden();
 await activate(page.locator('[data-graphics-action="close"]'));
 await expect(fps).toHaveCount(0);await expect(debug).toHaveCount(0);
 await activate(page.locator('[data-action="menu"]'));
 await expect(page.locator('[data-local-atlas-reset]')).toBeVisible();
 await expect(page.getByText('Local development',{exact:true})).toHaveCount(0);
 await page.screenshot({path:info.outputPath('reset-control.png'),fullPage:true});
 expect(errors).toEqual([]);
});
